name: Updater (WIP)

on:
  schedule:
    - cron: 0 0 * * 0

jobs:
  update:
    if: github.repository_owner == 'wowchemy'
    runs-on: ubuntu-latest
    steps:
      - uses: 
        with:
          feed-url: 
          readme-section: news
          branch: main
